// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('/home/hwjoo/01-active-projects/mobile-applications/sauron-mobile/node_modules/react');
var { Component } = React;
var ReactNative = require('/home/hwjoo/01-active-projects/mobile-applications/sauron-mobile/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('sauron-mobile', appParameters);
});
require('/home/hwjoo/01-active-projects/mobile-applications/sauron-mobile/index.android.js');